name: Build and Release Windows exe

on:
  push:
    branches: [ "main" ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.modcache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Determine version
        run: echo "VERSION=v0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Windows exe
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
          VERSION: ${{ env.VERSION }}
        run: |
          go mod download
          # build senza modificare il codice (nessun -X)
          go build -v -buildvcs=false -o "rinominatore_${VERSION}.exe" .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: "Windows build ${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rinominatore_${{ env.VERSION }}.exe
          asset_name: rinominatore_${{ env.VERSION }}.exe
          asset_content_type: application/octet-stream
